services:
  - type: web
    name: portfolio
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "20"
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /_next/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
